### PR TITLE
Fix Darwin stack struct naming conflict

### LINKED ISSUE #1: Darwin: Compilation error
Hello, very nice funny project!

I have an issue with `struct stack`, I think it's just a little conflict

```C
vm.c:65:22: error: typedef redefinition with different types ('struct stack' vs 'struct __darwin_sigaltstack')
typedef struct stack stack_t;
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_sigaltstack.h:48:29: note: previous definition is here
typedef _STRUCT_SIGALTSTACK     stack_t; /* [???] signal stack */
                                ^
vm.c:75:17: error: no member named 'size' in 'struct __darwin_sigaltstack'
    if (!stack->size) {
         ~~~~~  ^
```

### PR DESCRIPTION
**Pull request by pierre-emmanuelJ**
It's just a test to rename `stack` to `stackk`

Feel free to suggest a better variable name. Thanks

Fix #1

### CODE REVIEW

**Comment by motet-a** [comment]
Thank you!

**Comment by pierre-emmanuelJ** [comment]
I think `stack_toy_t` or `toy_stack_t` is better than `stackk_t`.
`stackk_t` was just an example

**Comment by motet-a** [comment]
It doesn’t really matter after all, it’s a dirty project written in a dirty programming language 🙃

**Comment by pierre-emmanuelJ** [comment]
https://golang.org

**Pull request merged**
